name: Currency Converter CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check index.html exists
        run: test -f index.html

      - name: Check style.css exists
        run: test -f style.css

      - name: Check script.js exists
        run: test -f script.js
